/*
 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 analytics.js v1.0
 Created: 2022-08-30T13:13:00+0000
*/
(function(m,d){if(!m.ORA.analytics){var a=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PRODUCT_READY,ORA.Event.STATUS_SUCCESS));ORA.common.TrackingPipeline.productIsReady("analytics");ORA.Debug.debug("setProductReady()","ANA")};ORA.analytics={dcsRef:null,plugins:{},addEventListener:ORA.addDOMEvent,eventQueue:null,version:{major:1,minor:0,inc:4},versionStr:"1.0.4",qryparams:{},dcsdelay:25,productReadyLatch:{},isSeedMessageTriggered:!1,elemOfEvent:function(b,c){var e=b.target||b.srcElement,
k=c||{};"string"===typeof c&&(k={},k[c.toUpperCase()]=1);for(;e&&e.tagName&&!k[e.tagName.toUpperCase()];)e=e.parentElement||e.parentNode;return e},multiTrack:function(b){try{return ORA.analytics.dcsRef.dcsMultiTrack(b),!1}catch(c){throw ORA.Debug.error("Error ORA.analytics.multiTrack: "+c.toSource(),"ANA"),c;}},instantiateExternal:function(){ORA.analytics.qryparams=ORA.common.QueryParamCache.getCache();ORA.analytics.loadJS=ORA.common.loadJS;ORA.analytics.eventQueue=new ORA.common.Queue;ORA.analytics.prettify=
ORA.common.JSONPrettify;ORA.analytics.dcsSaveCookie=ORA.common._setCookie;ORA.analytics.dcsDeleteCookie=ORA.common._deleteCookie;ORA.analytics.extendArray=ORA.common.extendArray;ORA.analytics.isFn=ORA.common.isFn;ORA.analytics.isArray=ORA.common.isArray;ORA.analytics.getCookieAsObj=ORA.common._getCookieAsObj;ORA.analytics.isEmpty=ORA.common.isEmpty;ORA.analytics.click=ORA.click;ORA.analytics.view=ORA.view;ORA.analytics.collect=ORA.collect;ORA.analytics.regPlugin=ORA.regPlugin;ORA.analytics.getTagId=
ORA.getTagId;ORA.analytics.getContextName=ORA.getContextName;ORA.analytics.getPluginsConfig=ORA.analytics._getPluginsConfig;ORA.analytics.setCookie=ORA.common._setCookie;ORA.analytics.deleteCookie=ORA.common._deleteCookie;ORA.analytics.getCookieRaw=ORA.common._getCookieRaw;ORA.analytics.getIEVer=ORA.common._getIEVer;ORA.analytics.isOptedOut=ORA.common._isOptedOut;ORA.analytics.setInfinityOptOut=ORA.common._setInfinityOptOut;ORA.analytics.addMutation=ORA.analytics.addMutation;ORA.analytics.rmMutation=
ORA.analytics.rmMutation;ORA.analytics.getFPC=function(){var b=ORA.analytics.getCookieAsObj(ORA.analytics.dcsRef.FPCConfig.name);return b&&b.id?b.id:null}},reset:function(){ORA.Debug.info("Analytics reset()","ANA");ORA.analytics.dscRef={}},execute:function(b){ORA.Debug.info("Analytics execute()","ANA");ORA.analytics.reset();var c=ORA.analyticsModule.prototype.oraConfigObj;b&&b.params&&ORA.hasVal(b.params)?(b=ORA.common.getMergedConfigs(c,b.params),ORA.analytics.setup(b)):ORA.analytics.setup(c)},performView:function(){ORA.common.clientID.isWaitForSetClientId&&
ORA.common.clientID.isClientIdSet&&(ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,ORA.view()),ORA.common.clientID.isWaitForSetClientId=!1)},registerLoaderEvents:function(){ORA.addEventHandler(ORA.Event.LOADER_RESET,this.reset);ORA.addEventHandler(ORA.Event.LOADER_EXECUTE,this.execute);ORA.common.clientID.isClientIdSet?this.performView():ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,this.performView)},setupPluginMgr:function(b){var c=ORA.analytics.getPluginCount("ora-plugins"),e=ORA.common.pluginMgr,
k=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - ora Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<c?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+c+"), deferring initPluginsCallback until plugins loaded","ANA"),e.setNumExpectedPlugins(c),e.setInitPluginsCallback(k),e.setInjectConfigsCb(ORA.analytics._getPluginsConfig,"ora-plugins")):(0===c&&b.waitForGetClientIDCallback.apply(b)?
(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+c+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS))):ORA.Debug.debug("setupPluginMgr - ora pluginCount("+c+"), not waiting on getId so countDown immediately","ANA"),k());e.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_ORA_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS));e=ORA.analytics.getPluginCount("hosted-plugins");var r=ORA.common.hostedPluginMgr,
q=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - Hosted Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<e?(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+e+"), deferring initPluginsCallback until plugins loaded","ANA"),r.setNumExpectedPlugins(e),r.setInitPluginsCallback(q),r.setInjectConfigsCb(ORA.analytics._getPluginsConfig),r.processHostedPlugins(b.config["hosted-plugins"])):
0===e&&b.waitForGetClientIDCallback.apply(b)?(ORA.Debug.debug("setupPluginMgr - hosted pluginCount("+c+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS)),k()):(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+c+"), not waiting on getId so countDown immediately","ANA"),q());r.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS))},setupProductCountdownLatch:function(b){var c=
2;b.waitForGetClientIDCallback.apply(b)&&(ORA.Debug.trace("prodCountdownLatch: waitForGetIdCall, latchCount++","ANA"),c++);ORA.analytics.productReadyLatch=new ORA.common.CountDownLatchClass(c,a,"ProductReadyLatch");ORA.Debug.debug("set productReadyLatch to "+c,"ANA")},setCheckSetDisableSeed:function(b){!0===b.s_disableSeed&&ORA.common.TrackingPipeline.disableSeed()},setWaitForSetClientId:function(b){!0===b.s_waitForSetClientId&&ORA.common.clientID.waitForSetClientId()},setup:function(b){try{ORA.Debug.debug("Analytics setup() started",
"ANA");this.instantiateExternal();this.setCheckSetDisableSeed(b);this.setWaitForSetClientId(b);var c=new ORA.analytics.dcs;c.init(b);this.setupProductCountdownLatch(c);c.setup();this.dcsRef=c;this.setupPluginMgr(this.dcsRef);this.registerLoaderEvents();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_SETUP_COMPLETE,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("Analytics setup() has finished","ANA")}catch(e){ORA.Debug.error("Analytics setup() failure",201,e,"ANA")}},addMutation:function(b,c,e){return ORA.common.TrackingPipeline.registerMutation(b,
c,e?e:2)},rmMutation:function(b){return ORA.common.TrackingPipeline.deregisterMutation(b)},getProductTimeout:function(){return ORA.common.TrackingPipeline.getProduct("analytics").timeout},_getPluginsConfig:function(b,c){var e={};ORA.analyticsModule.prototype.oraConfigObj[c]&&ORA.analyticsModule.prototype.oraConfigObj[c][b]&&(e=ORA.analyticsModule.prototype.oraConfigObj[c][b]);return e},getPluginCount:function(b){return ORA.analyticsModule.prototype.oraConfigObj[b]?ORA.common.extendObject(ORA.analyticsModule.prototype.oraConfigObj[b]).length():
0},getConfigParams:function(){var b=ORA.analytics,c={},e=ORA.analytics.dcsRef;e&&ORA.common.extendArray(["accountGuid","destinations","enabled","i18n","timezone"]).forEach(function(k){e[k]&&(c[k]=e[k])});c.version=b.version;c.versionStr=[c.version.major,c.version.minor,c.version.inc].join(".");c.dcsdelay=b.dcsdelay;return c},getEndPoint:function(){return"https://"+ORA.analytics.dcsRef.destinations[0].collectionServer+"/v3/"+ORA.analytics.dcsRef.destinations[0].accountGuid}};ORA.Debug.debug("ORA.analytics instantiation success",
"ANA")}})(window,window.document);
(function(m,d){ORA.analytics.dcs=function(){var a=m.RegExp?/dcs(uri)|(ref)|(aut)|(met)|(sta)|(sip)|(pro)|(byt)|(dat)|(p3p)|(cfg)|(redirect)|(cip)/i:"";this.exre=a;this.re={};this.plugins=this.plugins={};this.trackingData=this.trackingData={};this.DCS=this.DCS={};this.destinations=[];this.DCSext=this.DCSext={};this.errors=this.errors=[];this.FPCConfig=this.FPCConfig={};this._onsitedoms=[];this.gTempWtId=this.gWtAccountRollup=this.oraId="";this.prettify=ORA.analytics.prettify;return this};ORA.analytics.dcs.prototype=
{init:function(a){var b=a;try{ORA.Debug.debug("dcs init() start","ANA");"undefined"===typeof b&&(b={});this.config=b;var c=this;a=function(q,p){return b.hasOwnProperty(q)?b[q]:p};var e=function(q,p,h){return q?q.hasOwnProperty(p)?q[p]:h:h};this.extendArray=ORA.common.extendArray;this.errorlogger=function(q){ORA.Debug.error("Dcs",100,q,"ANA")};b.defaultCollectionServer||ORA.Debug.error("dcs init:  missing defaultCollectionServer");this.destinations=this.destinations=function(q){if(!q||0===q.length)throw Error("Destinations are not configured");
for(var p=[],h=0;h<q.length;h++){var t=e(q[h],"collectionServer",b.defaultCollectionServer),l={};l.collectionServer=l.collectionServer=t;l.timeout=l.timeout=e(q[h],"timeout",2E3);l.accountGuid=l.accountGuid=q[h].accountGuid;l.endpoint=l.endpoint=c.collectionEndpoint(t,q[h].accountGuid);p.push(l)}return p}(b.destinations);this.accountGuid=this.accountGuid=this.destinations[0].accountGuid;this.queue=this.queue=a("queue",[]);this.wtidTimeout=a("wtidTimeout",1E3);this.timezone=this.timezone=a("timezone",
-8);this.enabled=this.enabled=a("enabled",!0);this.i18n=this.i18n=a("i18n",!1);this.re=m.RegExp?c.i18n?{"%25":/%/g,"%26":/&/g,"%23":/#/g}:{"%25":/%/g,"%09":/\t/g,"%20":/\x20|\xA0|\x7F/g,"%23":/#/g,"%26":/&/g,"%2B":/\+/g,"%3F":/\?/g,"%5C":/\\/g,"%22":/"/g}:"";if(b.metanames){var k=b.metanames.toLowerCase();this.metanames=ORA.common.extendArray(k.split(","))}if(!0===b.metatagAuto||"true"===b.metatagAuto)this.metatagAuto=!0;this.skip_qp_no_value=this.skip_qp_no_value=a("skip_qp_no_value",!1);this.skip_qp_no_equals=
this.skip_qp_no_equals=a("skip_qp_no_equals",!1);this.skip_qp=this.skip_qp=a("skip_qp",!1);this.vtid=this.vtid=a("vtid",void 0);this.paidsearchparams=a("paidsearchparams","gclid");ORA.analytics.dcsdelay=b.dcsdelay||ORA.analytics.dcsdelay;this.delayAll=this.delayAll=a("delayAll",!1);this.preserve=this.preserve=a("preserve",!0);this._onsitedoms=a("onsitedoms","");ORA.common.isFn(this._onsitedoms.test)||(this._onsitedoms=ORA.common.extendArray(this._onsitedoms.toLowerCase().split(",")),this._onsitedoms.forEach(function(q,
p,h){h[p]=q.replace(/^\s*/,"").replace(/\s*$/,"")}));a("adimpressions",!1)&&(this.adclickparam=a("adsparam","WT.ac"));this.FPCConfig.enabled=this.FPCConfig.enabled=e(b.FPCConfig,"enabled",!0);this.FPCConfig.domain=this.FPCConfig.domain=e(b.FPCConfig,"domain","");this.FPCConfig.name=this.FPCConfig.name=e(b.FPCConfig,"name","ORA_FPC");this.FPCConfig.optOutCName=this.FPCConfig.optOutCName=e(b.FPCConfig,"optOutCName","Infinity.optout");this.FPCConfig.legacyCName=this.FPCConfig.legacyCName=e(b.FPCConfig,
"legacyCName","WT_FPC");this.FPCConfig.expiry=this.FPCConfig.expiry=e(b.FPCConfig,"expires",63113851500);63113851500<this.FPCConfig.expiry&&(this.FPCConfig.expiry=63113851500);this.FPCConfig.expireDate=new Date(this.getTime()+this.FPCConfig.expiry);this.FPCConfig.sessionOnly=0===this.FPCConfig.expiry||e(b.FPCConfig,"sessionOnly",!1);this.FPCConfig.autoTLD=this.FPCConfig.autoTLD=e(b.FPCConfig,"autoTLD",!1);b.cookieTypes&&(this.FPCConfig.enabled="none"!==b.cookieTypes.toLowerCase());var r={DNTBehavior:ORA.common._getConfigObject()&&
ORA.common._getConfigObject().DNTBehavior||"honorDNT",wtidTimeout:this.wtidTimeout,cookie:{enable:this.FPCConfig.enabled,name:this.FPCConfig.name,expires:this.FPCConfig.expiry,autoTLD:this.FPCConfig.autoTLD,sessionOnly:this.FPCConfig.sessionOnly,expireDate:this.FPCConfig.expireDate,domain:this.FPCConfig.domain},endpoint:{clientIDServer:this.destinations[0].collectionServer,accountGuid:this.destinations[0].accountGuid,protocol:"https"}};ORA.common.clientID.clientId=this.dcsGetFPC().id||null;ORA.common.clientID.setConfig(r);
this.plugins=b.plugins||{};ORA.analytics.dcs.prototype.action_collect=ORA.analytics.dcs.prototype.action_collect;ORA.analytics.dcs.prototype.init=ORA.analytics.dcs.prototype.init;ORA.analytics.dcs.prototype.setup=ORA.analytics.dcs.prototype.setup;ORA.analytics.dcs.prototype.dcsGetFPC=ORA.analytics.dcs.prototype.dcsGetFPC;ORA.analytics.dcs.prototype.dcsGetCookie=ORA.analytics.dcs.prototype.dcsGetCookie;ORA.analytics.dcs.prototype.dcsNavigation=ORA.analytics.dcs.prototype.dcsNavigation;this.registerProtocol();
ORA.Debug.debug("dcs init() finish","ANA");return this}catch(q){throw ORA.Debug.error("Error in init() - "+q.toString()),q;}},registerProtocol:function(){var a=ORA.common.TrackingPipeline;null===a.getCommProtocol(ORA.common.CommManager.GIF)&&(ORA.common._analyticsProtocol=ORA.common.protocols.gifProtocol,a.setCommProtocol(ORA.common.CommManager.GIF,ORA.common._analyticsProtocol))},collectionEndpoint:function(a,b,c){a||ORA.Debug.debug("Warning:  missing collectServer");a=a?a:"";if(!b)throw Error("accountGuid must be configured for "+
a);return"https://"+a+"/"+b+"/"+(c?c:"dcs.gif")},setReady:function(){ORA.Debug.debug("setReady()","ANA");this._readySet||(this.flushqueue(),this.redirectqueue(),this._readySet=!0)},flushqueue:function(){ORA.Debug.trace("flushqueue()","ANA");for(var a=0;a<this.queue.length;a++)this.doAction(this.queue[a]);this.queue=[]},redirectqueue:function(){var a=this;this.queue.push=function(b){a.doAction(b)}},dcsGetCookie:function(a){return ORA.analytics.dcsGetCookie(a,this.FPCConfig.name)},dcsIsFpcSet:function(a,
b){var c=ORA.analytics.getCookieAsObj,e=ORA.analytics.isEmpty;c=c(a);this.gTempWtId=c.id;return e(c)?2:b===c.id?0:3},dcsGetFPC:function(){return ORA.analytics.getCookieAsObj(this.FPCConfig.name)},dcsFPC:function(){var a=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";if(!ORA.analytics.isOptedOut())if(this.FPCConfig.enabled){this.trackingData.ce="1";var b=this.trackingData,c=this.FPCConfig.name,e=new Date,k=6E4*e.getTimezoneOffset()+36E5*this.timezone;e.setTime(e.getTime()+
k);var r=new Date(e.getTime());b.co_f=b.vtid="";b.vtvs=b.vt_f="";var q=ORA.analytics.getCookieAsObj(c);k=function(h){var t=q.id;null!==t&&(b.co_f=t,e.getTime()>r.getTime()+288E5&&r.setTime(e.getTime()),"undefined"===typeof h.gTempWtId||h.gTempWtId!==t)&&(b.vt_f="1",h.gTempWtId=t)};if(!ORA.common._isDNTSet()||"honorDNT"!==a){k(this);b.co_f=escape(b.co_f);b.vtid="undefined"===typeof this.vtid?b.co_f:this.vtid||"";q.id=b.co_f;this.FPCConfig.sessionOnly?ORA.common.mobile.nativeAppCkSend({name:c,value:q,
domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"session",timeout:this.FPCConfig.expiry}):ORA.common.mobile.nativeAppCkSend({name:c,value:q,domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"persisted",timeout:this.FPCConfig.expiry});a=ORA.common.isFpcSet(c,b.co_f);0!==a&&(b.co_f="","undefined"===typeof this.vtid&&(b.vtid=""),b.vt_f=a);var p={};ORA.common.extendObject(b).forEach(function(h,t){null!==h&&""!==h&&(p["WT."+t]=h)});return p}}else this.trackingData.ce=
"0",this.trackingData.vtid=this.vtid?this.vtid:""},dcsGetIdCallback:function(a){"undefined"!==typeof a&&(this.oraId||(this.oraId=a),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS)));this.setReady();ORA.analytics.productReadyLatch.countDown()},waitForGetClientIDCallback:function(){var a=ORA.common._getCookieAsObj(),b=2!==this.dcsIsFpcSet(this.FPCConfig.name),c=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";c=ORA.common._isDNTSet()&&
"honorDNT"===c;return ORA.common._isOptedOut(a)||b||!this.FPCConfig.enabled||c||ORA.common._getConfigObject().s_waitForSetClientId?!1:!0},setup:function(){try{var a=this,b=function(c){a.dcsGetIdCallback.apply(a,[c])};this.FPCConfig.enabled?ORA.common.mobile.delay(function(){a.waitForGetClientIDCallback.apply(a)?ORA.common.clientID.getClientID(b):a.setReady.apply(a,[])},"ANA",ORA.analyticsModule.prototype.oraConfigObj):this.setReady();this.enQueue("collect",{element:void 0,event:void 0});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_DCS_SETUP,
ORA.Event.STATUS_SUCCESS));ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,function(c){a.oraId=c.params},null,!0);ORA.addEventHandler(ORA.Event.CLEAR_CLIENT_ID,function(){ORA.analytics.pageAnalysis["WT.co_f"]=ORA.analytics.pageAnalysis["WT.vtid"]=null},null,!0);return this}catch(c){this.errors.push(c),this.errorlogger(c)}},addQueryParameters:function(a,b){var c=this.DCS;if(0<a.length()&&!this.skip_qp){a.forEach(function(r,q){var p=r;if(!((this.skip_qp_no_value||this.skip_qp_no_equals)&&"undefined"===
typeof r||this.skip_qp_no_equals&&""===r)){if("undefined"===typeof r||null===r)p="undefined";c[q]=p}},this);var e=this.paidsearchparams.length?this.paidsearchparams.toLowerCase().split(","):[];for(var k=0;k<e.length;k++)if(ORA.common.QueryParamCache.contains(e[k],!0)){b.srch="1";break}}},dcsVar:function(){var a=this.trackingData;this.i18n&&(a.le="string"===typeof d.defaultCharset?d.defaultCharset:"string"===typeof d.characterSet?d.characterSet:"unknown");a.tv=ORA.analytics.versionStr;var b=ORA.common.QueryParamCache.getCache();
this.addQueryParameters(b,a);!0===this.metatagAuto&&ORA.common.visitMetaTags(this.dcsMetaTagsAutoScrape,d,this.DCSext);this.metanames&&ORA.common.visitMetaTags(this.dcsMetaTagArrScrape(this.metanames),d,this.DCSext)},dcsMetaTagArrScrape:function(a){return function(b,c,e){b=b.toLowerCase();-1!==a.indexOf(b)&&(e["meta_"+b]=c)}},dcsMetaTagsAutoScrape:function(a,b,c){0===a.indexOf("ORA.")?c[a]=b:0===a.indexOf("DCS.")?(a=a.split("DCS."),a[1]&&(c[a[1]]=b)):0===a.indexOf("DCSext.")&&(a=a.split("DCSext."),
a[1]&&(c[a[1]]=b))},getPageAnalysis:function(){var a=ORA.analytics.dcsRef.dcsFPC(),b=ORA.common.extendArray;ORA.analytics.pageAnalysis?b(["vt_f"]).forEach(function(c){ORA.analytics.pageAnalysis["WT."+c]&&delete ORA.analytics.pageAnalysis["WT."+c]}):ORA.analytics.pageAnalysis=ORA.analytics.dcsRef.genPageAnalysis();return ORA.paramsMerge(ORA.analytics.pageAnalysis,a)},genPageAnalysis:function(){try{if(ORA.fireEvent(new ORA.Event(ORA.Event.ANA_BEFORE_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS)),!ORA.analytics.isOptedOut()){var a=
this.trackingData,b=this.DCS,c=this.DCSext,e=this.i18n;e&&(a.dep="");var k={},r;for(r in b)b.hasOwnProperty(r)&&void 0!==b[r]&&"function"!==typeof b[r]&&(k[r]=b[r]);for(var q in a)a.hasOwnProperty(q)&&""!==a[q]&&void 0!==a[q]&&"function"!==typeof a[q]&&(k["WT."+q]=a[q]);for(var p in c)c.hasOwnProperty(p)&&""!==c[p]&&void 0!==c[p]&&"function"!==typeof c[p]&&(e&&(a.dep=0===a.dep.length?p:a.dep+";"+p),k[p]=c[p]);e&&0<a.dep.length&&(k["WT.dep"]=a.dep);ORA.Debug.superfine("pageAnalysis: "+this.prettify(k),
"ANA");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS));return k}}catch(h){ORA.Debug.error("error in pageAnalyze: "+h.toString())}},doRequest:function(){var a=this.destinations,b=this.getPageAnalysis;ORA.common.TrackingPipeline.registerMutation("analyticsAnnotate",function(c){if(c.params.mutation&&(!0===c.params.mutation.pageview||!0===c.params.mutation.conversion||!0===c.params.mutation.click||!0===c.params.mutation.collect&&!1!==c.params.sendSessionInfo||
!0===c.params.mutation.view)){var e=b(),k;for(k in e)e.hasOwnProperty(k)&&!c.getParam(k)&&c.setParam(k,e[k]);c.setParam("ora.tag_id",ORA.getTagId());c.setParam("ora.tag_config",ORA.getContextName());ORA.Debug.debug(c.params.desc?"annotating "+c.params.desc+" w/ analytics page analysis":"annotating w/ analytics page analysis","ANA");ORA.Debug.trace("annotating payload w/ "+ORA.analytics.prettify(e),"ANA");ORA.Debug.trace("Endpoints: "+ORA.analytics.prettify(a),"ANA");if("collect"!==c.params.desc)for(e=
0;e<a.length;e++)c.endpoints.push({endpoint:a[e].endpoint,timeout:a[e].timeout,conf:ORA.analytics.dcsRef,protocolType:ORA.common.CommManager.GIF});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PV_MUTATE,ORA.Event.STATUS_SUCCESS))}},1);ORA.Debug.debug("doRequest() - register mutation","ANA")},pageAnalyze:function(){ORA.Debug.trace("pageAnalyze()");this.dcsVar();this.adclickparam&&0<this.adclickparam.length&&this.dcsAdSearch();this.pageAnalyzehasRun=!0},getTime:function(){return(new Date).getTime()},dumpCounter:0,
spinLock:function(a){for(var b=this.getTime();this.getTime()-b<a;)this.dumpCounter++},enQueue:function(a,b){var c=a;ORA.Debug.debug("enQueue() - action: "+JSON.stringify(c)+" msg: "+JSON.stringify(b),"ANA");c||(c="collect");this.queue.push({action:c,message:b})},doAction:function(a){ORA.Debug.debug("doAction() - cmd: "+this.prettify(a),"ANA");var b="action_"+a.action;a=a.message;this.pageAnalyzehasRun||this.pageAnalyze();a.event&&!a.element&&(a.element=ORA.analytics.elemOfEvent(a.event,{A:1}));if(ORA.analytics.isFn(this[b]))this[b](a)},
action_collect:function(a){ORA.Debug.debug("action_collect()","ANA");this.doRequest(a)},dcsIsOnsite:function(a,b){var c=a;if(0<c.length){c=c.toLowerCase();if(c===window.location.hostname.toLowerCase())return!0;if(ORA.analytics.isFn(b.test))return b.test(c);if(0<b.length)for(var e=b.length,k=0;k<e;k++)if(c===b[k])return!0}return!1},dcsNavigation:function(a,b){var c="",e="",k=b.length,r;for(r=0;r<k;r++){var q=b[r];if(q.length&&(e=ORA.analytics.elemOfEvent(a,q),c=e.getAttribute&&e.getAttribute("id")?
e.getAttribute("id"):"",e=e.className||"",c.length||e.length))break}return c.length?c:e},dcsAdSearch:function(){if(d.links){var a=this.adclickparam+"\x3d",b=a.length;a=new RegExp(a,"i");var c=d.links.length,e=d.URL+"",k=e.search(a);if(-1!==k){var r=e.indexOf("\x26",k);var q=-1!==r?e.substring(k,r):e.substring(k,e.length);var p=new RegExp(q+"(\x26|#)","i")}for(e=0;e<c;e++)if(d.links[e].href){var h=d.links[e].href+"";q&&0<q.length&&(h=h.replace(p,"$1"));r=h.search(a);-1!==r&&(k=r+b,r=h.indexOf("\x26",
k),r=-1!==r?h.substring(k,r):h.substring(k,h.length),this.trackingData.ad=this.trackingData.ad?this.trackingData.ad+";"+r:r)}}}};ORA.Debug.debug("dcs class loaded","ANA")})(window,window.document);
(function(m,d,a){ORA.analytics.find=function(b){ORA.analytics.selectorEngine||(ORA.analytics.selectorEngine=ORA.analytics.findSelector());return ORA.analytics.selectorEngine(b)};ORA.analytics.findSelector=function(){var b=/MSIE (\d+)/.exec(a.userAgent);b=b?b[1]:99;var c=d.body;if(d.querySelectorAll&&c&&8<b)return function(e){return c.querySelectorAll(e)};if(m.jQuery)return m.jQuery.find;if(m.Sizzle)return m.Sizzle;if(m.YAHOO&&YAHOO.util&&YAHOO.util.Selector)return YAHOO.util.Selector.query;if("qwery"in
m)return qwery;m.YUI&&YUI().use("node",function(e){return e.all});return d.querySelectorAll&&c?function(e){return c.querySelectorAll(e)}:function(){return[]}};ORA.Debug.debug("selectorEngine initialized","ANA")})(window,window.document,window.navigator);
(function(){function m(){if(this.href){var f=this.href;if(l.autoSelect||l.addHash){f=this.href;var g=h()||{};f&&-1<f.indexOf("#")||!g.id||!l.guard||(l.encode&&window.btoa&&(g.id=btoa(g.id)),ORA.Debug.debug("Adding hash to href: "+f+"#xd_co_f\x3d"+g.id+l.guard,"crossDomain-ANA"),f=f+"#xd_co_f\x3d"+g.id+l.guard)}if(l.autoSelect&&f===this.href||!l.autoSelect&&l.addParam)if(f=this.href,g=h(),f&&(!g||g.id)&&l.guard){l.encode&&window.btoa&&(g.id=btoa(g.id));ORA.Debug.debug("Adding parameters to href: "+
f+"?xd_co_f\x3d"+g.id+l.guard,"crossDomain-ANA");g="xd_co_f\x3d"+g.id;var n=f.replace(/(&|\?)xd_co_f=[^&|#]*/,"$1"+g);f&&-1===f.indexOf("xd_co_f\x3d")&&(n=-1!==f.indexOf("?")?-1===f.indexOf("#")?f.split("?")[0]+"?"+g+"\x26"+f.split("?")[1]:f.split("#")[0]+"\x26"+g+"#"+f.split("#")[1]:-1!==f.indexOf("#")?f.split("#")[0]+"?"+g+"#"+f.split("#")[1]:f+"?"+g);f=n}this.href=f}}function d(f){var g=/[^A-Z0-9+\/=]/i,n=f.length;if(!n||0!==n%4||g.test(f))return!1;g=f.indexOf("\x3d");return-1===g||g===n-1||g===
n-2&&"\x3d"===f[n-1]}function a(f,g){var n=f.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),u;(n=(new RegExp("[\\?\x26]"+n+"\x3d([^\x26#]*)")).exec(g||location.search))&&(u=decodeURIComponent(n[1].replace(/\+/g," ")))&&d(u)&&window.atob&&(u=atob(u));return u}function b(f,g){var n,u=f.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");(u=(new RegExp("[#]"+u+"\x3d(.*)"+l.guard)).exec(g||location.hash))&&(n=decodeURIComponent(u[1].replace(/\+/g," ")))&&d(n)&&window.atob&&(n=atob(n));return n}function c(f,g,n,
u){function v(y){return function(z){for(var A=z.target;A&&A!==document&&!this.wasCalled;){var B=A;if("A"===B.nodeName){var C=B.cloneNode(!0);C.href=B.href;B=C}B.matches&&B.matches(f)&&!B.matches(g)&&(u.call(A,z),this.wasCalled=!0);A=A.parentNode}}.apply(this,[y])}if(document.addEventListener)document.addEventListener(n,v);else{var w=n;"click"===n&&(w="mousedown");document.attachEvent("on"+w,v)}}function e(f){if(t&&f.payload["wt.co_f"]!==t){ORA.Debug.debug("Resessionizing from "+f.payload["wt.co_f"]+
"to"+t,"crossDomain-ANA");f.payload["wt.vtid"]===f.payload["wt.co_f"]&&(f.payload["wt.vtid"]=t);f.payload["wt.co_f"]=t;f=h();f.id=t;var g=ORA.analytics.dcsRef,n=g.FPCConfig.expireDate||new Date((new Date).getTime()+63113851500),u="";g.FPCConfig.sessionOnly||(u="; expires\x3d"+n.toGMTString());ORA.analytics.setCookie(g.FPCConfig.name||"ORA_FPC",{id:f.id},""===g.FPCConfig.domain?u+"; path\x3d/":u+"; path\x3d/; domain\x3d"+g.FPCConfig.domain)}ORA.analytics.rmMutation("crossDomain")}function k(f){for(var g in f)f.hasOwnProperty(g)&&
(l[g]=f[g]);return l}function r(f){if("localhost"===f){f=[location.hostname];var g=['A[href*\x3d"'+location.hostname+'"]'];!l.ignoreOnsiteDoms&&ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&!f.test&&""!==ORA.analytics.dcsRef._onsitedoms[0]&&(f=ORA.analytics.dcsRef._onsitedoms);if(f.test)ORA.Debug.debug("crossDomain does not support using regex for onsitedom list - using localhost","crossDomain-ANA");else{g=[];""===f&&(f=[location.host]);for(var n=0;n<f.length;n++)g.push('A[href*\x3d"'+f[n]+
'/"]')}g.push('A[href*\x3d"javascript:"],A[href*\x3d"mailto:"]');f=g.join(",")}ORA.Debug.debug("CrossDomain using black list: "+f,"crossDomain-ANA");return f}function q(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||
function(f){f=(this.document||this.ownerDocument).querySelectorAll(f);var g=f.length;for(--g;0<=g&&f.item(g)!==this;)--g;return-1<g})}function p(){if(!l.enable)return ORA.Debug.info("crossDomain Plugin is disabled","crossDomain-ANA"),!0;if(!(l.autoSelect||l.addHash||l.addParam))return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID","crossDomain-ANA"),!0;var f=ORA.getIEVer();return f&&9>f?(ORA.Debug.info("Browser is not compatible, requires IE9+","crossDomain-ANA"),
!0):!1}function h(){var f=ORA.analytics.dcsRef,g="ORA_FPC";f&&f.FPCConfig&&f.FPCConfig.name&&(g=f.FPCConfig.name);var n={};f=RegExp(""+g+"[^;]+").exec(document.cookie)||"";f=decodeURIComponent(f.toString().replace(/^[^=]+./,""));try{f&&f.split(":").forEach(function(u){n[u.split("\x3d")[0]]=u.split("\x3d")[1]})}catch(u){return null}return n}var t,l={enable:!0,guard:"~",addHash:!0,addParam:!1,autoSelect:!1,encode:!0,blackListSelector:"localhost",whiteListSelector:"A",testSessionId:!1,ignoreOnsiteDoms:!1},
x=function(){var f=document.createElement("br");return function(g){try{f.querySelector(g)}catch(n){return!1}return!0}}();ORA.Debug.info("crossDomain plugin Register (blocking)","crossDomain-ANA");ORA.regPlugin("crossDomain",function(f,g){var n=g||function(){},u=f.config;q();try{k(u);if(p())return n();var v=l.whiteListSelector,w=r(l.blackListSelector);if(!x(v))return ORA.Debug.info("whiteList selector is invalid - exiting: "+v,"crossDomain-ANA"),n();if(!x(w))return ORA.Debug.info("blackList selector is invalid - exiting: "+
w,"crossDomain-ANA"),n();ORA.Debug.debug("binding using whiteList:"+v+" blackList: "+w,"crossDomain-ANA");c(v,w,"mousedown",m);c(v,w,"click",m);if((t=b("xd_co_f")||a("xd_co_f")||a("ora_vtid"))||l.testSessionId)ORA.Debug.debug("Adding Mutation","crossDomain-ANA"),ORA.analytics.addMutation("crossDomain",e,3);ORA.Debug.debug("crossDomain Start Init Complete (unblock)","crossDomain-ANA");return n()}catch(y){return ORA.Debug.debug("crossDomain plugin Init Error (unblock)"+y.message,"crossDomain-ANA"),
n()}},{blockCollect:!0});ORA.analytics.plugins.crossDomain={};ORA.analytics.plugins.crossDomain.testNode=function(f){return eval(f)}})();
(function(){var m={cfg:{standardEvents:{download:!1,offsite:!1,onsite:!1,rightclick:!1,anchor:!1,javascript:!1,scrollTracking:!1},eventList:{},cookieName:"ORA_EVENT",downloadtypes:"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip",socialTypes:{},trackSocial:!0},init:function(d,a){var b=d.config||{},c=a||function(){};ORA.Debug.debug("Event Track plugin Start Init","ANA-ET");try{for(var e in b)b.hasOwnProperty(e)&&(m.cfg[e]=b[e]);if(void 0!==m.cfg.enable&&!m.cfg.enable)return ORA.Debug.debug("Event Track plugin is disabled - exiting",
"ANA-ET"),c();var k=ORA.getIEVer();if(k&&9>k)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-ET"),c();ORA.Debug.info("Adding standard events","ANA-ET");m._addStandardEvents();if(!document.querySelectorAll)return ORA.Debug.info("Event Track plugin requires querySelectorAll function","ANA-ET"),c(),!1;m._addMatches();ORA.Debug.info("Binding to objects","ANA-ET");m._bind()}catch(r){ORA.Debug.error("Event Track plugin Init Error"+r.message,"ANA-ET"),c()}ORA.analytics.rmMutation("evt",
m.deferMutation);ORA.Debug.debug("Adding deferred mutation","ANA-ET");ORA.analytics.addMutation("evt",m.deferMutation);ORA.Debug.debug("Calling deferred message flush","ANA-ET");m._flushMsg();c();ORA.Debug.debug("Event Track plugin Start Init Complete","ANA-ET")},_getFullUrl:function(d){if("A"===d.nodeName){var a=d.cloneNode(!0);a.href=d.href;return a}return d},_pageWillReloads:function(d){var a=[];try{a=d.split("#");var b=window.location.href.split("#")[0]}catch(c){return ORA.Debug.error(c.message),
!1}return 1===a.length?!0:a[0]!==b},_eventCallback:function(d,a){try{for(var b=d.eventTrigger&&d.eventTrigger.split(" ")||["mousedown"],c=function(k,r,q){q._evtMsg(k);try{var p=q._fnCreator(d.eventCallback)(k,r);q._isEmptyObj(p)||(p.defer&&(p.data["wt.isDeferred"]="1"),ORA.click({data:p.data}),q._fnCreator(d.fnFinishCallback)(k))}catch(h){ORA.Debug.error("Event Track error in event callback: "+h.message,"ANA-ET")}},e=0;e<b.length;e++)"immediate"!==b[e].toLowerCase()?(ORA.Debug.info("Event Track for "+
a+" bind to "+d.selector+" event: "+b[e],"ANA"),this._delegate(document,b[e].toLowerCase(),d.selector,c,d,this)):(ORA.Debug.info("Event Track Immediate: "+a,"ANA"),c(null,null,this))}catch(k){ORA.Debug.error("Error binding adding selector for: "+a+" err: "+k.message,"ANA-ET")}},_delegate:function(d,a,b,c,e,k){function r(p){return function(h,t,l){var x=h.target||h.srcElement,f=x;"scroll"===h.type&&c.call(null,h,t,l);for("A"===x.nodeName&&x.href&&(f=m._getFullUrl(x));f&&f!==document;)f.matches(b)&&
c.call(f,h,t,l),f=f.parentNode}.apply(this,[p,e,k])}if(d.addEventListener)d.addEventListener(a,function(p){r(p)});else{var q=a;"click"===a&&(q="mousedown");d.attachEvent("on"+q,function(p){r(p)})}},_bind:function(){var d=this.cfg.eventList,a;for(a in d)d.hasOwnProperty(a)&&this._eventCallback(d[a],a)},_evtMsg:function(d){if(d){var a="Event Triggered:"+d.type+" node:"+(d.srcElement||d.target).nodeName+" #";a+=(d.srcElement||d.target).id+" class:"+(d.srcElement||d.target).className;ORA.Debug.info(a,
"ANA-ET")}else ORA.Debug.info("Event Triggered for immediate event","ANA-ET")},_fnCreator:function(d){return"string"===typeof d?new Function("e",d):"function"===typeof d?d:function(){}},_addMatches:function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,Element.prototype.matches=Element.prototype.matches||
Element.prototype.webkitMatchesSelector||function(d){d=(this.document||this.ownerDocument).querySelectorAll(d);var a=d.length;for(--a;0<=a&&d.item(a)!==this;)--a;return-1<a})},_isRightClick:function(d){d=d||window.event;if(d.which)d=3===d.which;else if(d.button)d=2===d.button;else return!1;return d},_getHrefInfo:function(d){var a=d.target||d.srcElement||{},b={},c=a,e=document.createElement("a");a=this._findA(a);if(!a.href)return{};e.href=a.href;b.dcssip=e.hostname?e.hostname.split(":")[0]:window.location.hostname;
e.pathname&&0!==e.pathname.indexOf("/")?b.dcsuri="/"+e.pathname:b.dcsuri=e.pathname?e.pathname:"/";e.search&&(b.dcsqry=e.search.substring(e.search.indexOf("?")+1,e.search.length));b.dcsref=document.referrer;b["WT.nv"]=this._findNV(c,d,{DIV:1,TABLE:1});b["WT.dl"]="24";return this._cleanPayload(b)},_findNV:function(d,a,b){for(;d&&d!==document&&d.tagName&&!b[d.tagName];)d=a.parentElement||d.parentNode;return d!==document?d.id||d.className:""},_cleanPayload:function(d){for(var a in d)d.hasOwnProperty(a)&&
!d[a]&&delete d[a];return d},_findA:function(d){for(;d&&"A"!==d.nodeName;)d=d.parentNode;return d},_checkOnsiteDom:function(d,a){var b=ORA.analytics.dcsRef._onsitedoms;b.test||(1===b.length&&""===b[0]&&(b=[location.host.split(":")[0]]),b=new RegExp(b.join(",").toLowerCase().replace(",","|").replace(/^\s*/,"").replace(/\s*$/,"")));return!(m._isRightClick(a)||!b.test(d.hostname))},_checkDeferred:function(d,a){return(a.href&&m._getFullUrl(a).matches('A[href*\x3d"'+location.host+'/"]')?0:void 0!==a.target&&
"_blank"!==a.target)?{defer:!0,data:d}:{defer:!1,data:d}},_isEmptyObj:function(d){if("object"!==typeof d)return!0;for(var a in d)if(d.hasOwnProperty(a))return!1;return!0},_deferMutation:function(d){try{d.params&&d.params.payload["wt.isdeferred"]&&(ORA.Debug.debug("Deferring payload, saving into cookie","ANA-ET"),delete d.params.payload["wt.isdeferred"],d.params.payload["wt.deferredpayload"]="1",this._saveMsg(d),d.sendDisable())}catch(a){}},deferMutation:function(d){m._deferMutation(d)},_saveMsg:function(d){if(window.JSON){var a=
[],b=this.cfg.cookieName;ORA.analytics.getCookieRaw(b)&&(a=ORA.common.decode(ORA.analytics.getCookieRaw(b)));a.push(d.payload);ORA.setCookie(b,ORA.common.encode(a),"; path\x3d/");ORA.Debug.debug("Saved payload into cookie: "+document.cookie,"ANA-ET")}else ORA.Debug.debug("Browser version does not support saving payloads into cookies","ANA-ET")},_flushMsg:function(){var d=this.cfg.cookieName;try{if(ORA.analytics.getCookieRaw(d)){ORA.Debug.debug("Found ORA_EVENT cookie - sending events","ANA-ET");var a=
ORA.common.decode(ORA.analytics.getCookieRaw(d));ORA.Debug.debug("Found "+a.length+" deferred Payloads - sending now","ANA-ET");for(var b=0;b<a.length;b++){var c=a[b],e=new Date;c["wt.ets"]=(new Date(e.getTime()+6E4*e.getTimezoneOffset())).getTime();ORA.click({data:c})}ORA.deleteCookie(d,"/")}}catch(k){ORA.Debug.debug("Error parsing ORA_EVENT cookie - removing cookie"),ORA.deleteCookie(d,"/")}},_addStandardEvents:function(){var d={download:"_addDownloadTracking",offsite:"_addOffsiteTracking",onsite:"_addOnsiteLinkTracking",
anchor:"_addAnchorTracking",rightclick:"_addRightClickTracking",javascript:"_addJavaScriptTracking",scrollTracking:"_addScrollTracking"},a;for(a in this.cfg.standardEvents)if(this.cfg.standardEvents.hasOwnProperty(a)&&this.cfg.standardEvents[a])this[d[a]]()},_addDownloadTracking:function(){ORA.Debug.info("Event Track plugin Add download tracking","ANA-ET");for(var d=[],a=m.cfg.downloadtypes.toLowerCase().split(","),b=0;b<a.length;b++)d.push('A[href*\x3d".'+a[b]+'"]');m.cfg.eventList.download={eventTrigger:"click",
selector:d.join(","),eventCallback:function(c){var e=c.target||c.srcElement||c.target||{},k=m._getHrefInfo(c);ORA.Debug.debug("Download Callback Called");if(m._isRightClick(c)||!k)return{};k["WT.ti"]="Download:"+e.textContent||e.innerText;k["WT.dl"]="20";return m._checkDeferred(k,e)}}},testSocial:function(d,a,b){for(var c=0;c<d[a].length;c++)if(-1<b.toLowerCase().indexOf(d[a][c].toLowerCase()))return!0;return!1},isSocial:function(d){var a=m.cfg.socialTypes,b;for(b in a)if(a.hasOwnProperty(b)&&m.testSocial(a,
b,d))return b;return null},_addOnsiteLinkTracking:function(){ORA.Debug.info("Event Track plugin add onsite link tracking","ANA-ET");for(var d=m.cfg.downloadtypes.toLowerCase().split(","),a=':not([href*\x3d"javascript:"])',b=0;b<d.length;b++)a+=':not([href*\x3d".'+d[b]+'"])';d=['A:not([href^\x3d"//"])'+a];b=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(b=ORA.analytics.dcsRef._onsitedoms);if(!b.test){if(""===b||0===b[0].length)b=[location.hostname];for(var c=0;c<b.length;c++)d.push('A[href*\x3d"'+
b[c]+'"]'+a)}m.cfg.eventList.onsite={eventTrigger:"click",selector:d.join(","),eventCallback:function(e){var k=e.target||e.srcElement||{},r=m._getHrefInfo(e);ORA.Debug.debug("Onsite Link Callback Called");if(m._isEmptyObj(r))return{};for(;k&&"A"!==k.nodeName;)k=k.parentNode;if(!m._checkOnsiteDom(k,e))return ORA.Debug.debug("Onsite Link Callback Called - fails onsite test. Exiting"),{};r["WT.ti"]="Onsite:"+r.dcssip+r.dcsuri;r.dcsqry&&(r["WT.ti"]+=r.dcsqry);r["WT.dl"]="1";return{defer:m._pageWillReloads(k.href),
data:r}}}},_addOffsiteTracking:function(){ORA.Debug.info("Event Track plugin add offsite tracking","ANA-ET");var d=['A:not(A[href*\x3d"javascript:"])'],a=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(a=ORA.analytics.dcsRef._onsitedoms);if(!a.test){d=[];""===a&&(a=[location.host]);for(var b=0;b<a.length;b++)d.push('A:not([href*\x3d"'+a[b]+'"]):not([href*\x3d"javascript:"])')}m.cfg.eventList.offsite={eventTrigger:"click",selector:d.join(","),eventCallback:function(c){var e=
c.target||c.srcElement||{},k=m._getHrefInfo(c);ORA.Debug.debug("Offsite Callback Called");if(m._isEmptyObj(k))return{};for(;e&&"A"!==e.nodeName;)e=e.parentNode;var r=m.isSocial(e.href);r&&m.cfg.trackSocial&&(k["WT.soc_action"]=r+":click");if(m._checkOnsiteDom(e,c))return ORA.Debug.debug("Offsite Callback Called - fails offsite test exiting"),{};k["WT.ti"]="Offsite:"+k.dcssip+k.dcsuri;k.dcsqry&&(k["WT.ti"]+=k.dcsqry);k["WT.dl"]="24";return m._checkDeferred(k,e)}}},_addRightClickTracking:function(){ORA.Debug.info("Event Track plugin add right click tracking",
"ANA-ET");for(var d=[],a=m.cfg.downloadtypes.toLowerCase().split(","),b=0;b<a.length;b++)d.push('A[href*\x3d".'+a[b]+'"]');m.cfg.eventList.rightClick={eventTrigger:"mousedown",selector:d.join(","),eventCallback:function(c){ORA.Debug.debug("Rightclick Callback Called");if(!m._isRightClick(c)&&!m.cfg.testRightClick)return ORA.Debug.debug("RightClick Callback Called - exiting fails rightclick test"),{};var e=c.element||c.srcElement||c.target||{};c=m._getHrefInfo(c);if(!c)return{};c["WT.ti"]="RightClick:"+
e.textContent||e.innerText;c["WT.dl"]="25";return{data:c}}}},_addJavaScriptTracking:function(){ORA.Debug.info("Event Track plugin add javascript tracking","ANA-ET");m.cfg.eventList.javaScript={eventTrigger:"click",selector:'A[href*\x3d"javascript:"]',eventCallback:function(d){var a=d.element||d.srcElement||d.target||{};d=m._getHrefInfo(d);if(m._isEmptyObj(d))return{};ORA.Debug.debug("JavaScript Callback Called");d["WT.ti"]=a.innerHTML?"JavaScript:"+a.innerHTML:"JavaScript:";d["WT.dl"]="22";d.dcssip=
window.location.hostname;d.dcsuri=a.href;return{data:d}}}},_addAnchorTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");var d=window.location.pathname.split("/").pop();m.cfg.eventList.anchorTracking={eventTrigger:"click",selector:'A[href^\x3d"#"],A[href*\x3d"'+d+'#"]',eventCallback:function(a,b){var c=a.target||a.srcElement||{},e=m._getHrefInfo(a);if(m._isEmptyObj(e))return{};for(ORA.Debug.debug("Anchor Callback Called");c&&"A"!==c.nodeName;)c=c.parentNode;if(!m._checkOnsiteDom(c,
a)||!b.hasHash(c))return ORA.Debug.debug("Anchor Callback Called - no Hash address found, or offsite link - exiting hash:"+c.hash,"ANA-ET"),{};e["WT.ti"]="Anchor:"+(c.hash||"#");e["WT.dl"]="21";b.checkFragment(c);return{data:e}},hasHash:function(a){return a.hash&&-1<a.hash.indexOf("#")},checkFragment:function(a){ORA.analytics.plugins&&ORA.analytics.plugins.fragment&&ORA.analytics.plugins.fragment.updateFragData&&ORA.analytics.plugins.fragment.updateFragData(a.hash)}}},_addScrollTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking",
"ANA-ET");m.cfg.eventList.scrollTracking={selector:"",eventTrigger:"scroll",eventCallback:function(){window.scrollTracker||(window.scrollTracker={1:!1,2:!1,3:!1,4:!1});var d=document.documentElement,a=document.body;d=Number((("CSS1Compat"===document.compatMode?d.clientHeight||window.innerHeight||0:a.clientHeight||0)+(window.pageYOffset||d&&d.scrollTop||a.scrollTop))/Math.max(a.scrollHeight,d.scrollHeight,a.offsetHeight,d.offsetHeight,a.clientHeight,d.clientHeight)*4).toFixed(0);if(!window.scrollTracker[d]){window.scrollTracker[d]=
!0;for(var b in window.scrollTracker)window.scrollTracker.hasOwnProperty(b)&&b<d&&!window.scrollTracker[b]&&(window.scrollTracker[b]=!0,ORA.click({data:{"WT.page_scroll_depth":25*b,"WT.dl":"71"}}));return{data:{"WT.page_scroll_depth":25*Number(d),"WT.dl":"71"}}}return{}}}},addTracking:function(d,a){"object"===typeof d&&"string"===typeof a?m._eventCallback(d,a):ORA.Debug.debug("Ignoring addTrack call - obj or trigger type error","ANA-ET")}};ORA.regPlugin("evtTrack",m.init);ORA.analytics.plugins.evtTrack||
(ORA.analytics.plugins.evtTrack={});ORA.analytics.plugins.evtTrack.addTracking=m.addTracking;ORA.analytics.plugins.evtTrack._flushMsg=m._flushMsg;ORA.analytics.plugins.evtTrack.eventTrack=m})();
(function(){ORA.Debug.debug("Behaviour Tracking Plugin init start","ANA-SBT");var m={enable:!1},d,a,b=function(g,n){try{return(new RegExp(n)).test(g)}catch(u){return ORA.Debug.error("Invalid regex for url match provided Behaviour Tracking"),!1}},c=function(g,n){if(!n||!n.pattern)return!0;var u=g.toLowerCase(),v=n.pattern;v=v.toLowerCase();switch(n.criteria.toLowerCase()){case "isnot":return!b(u,v+"$");case "is":return b(u,"^"+v+"$");case "containsnot":return!b(u,v);case "startswith":return b(u,"^"+
v);case "endswith":return b(u,v+"$");case "regex":case "contains":return b(u,v);default:throw Error("Criteria `"+n.criteria+"` is undefined.. Please verify");}},e=function(g){g["user-agent"]=navigator.userAgent;ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:g})},k=function(g,n){var u={};u["wt.ev"]=n.name;u["ora.type"]=n.type;var v=n.parameters;if(v&&0<v.length)for(var w=0;w<v.length;w++){var y=v[w];y.value?u[y.name]=y.value:
y.dom_selector?u[y.name]=ORA.common.getValueFromDOM(y.dom_selector,n.apply_for_similar,g):ORA.Debug.error("Invalid parameter keys","ANA-SBT")}e(u)},r=function(g,n){g&&!g[n.id]&&(g[n.id]=!0,ORA.common.addEventListenersOnDOMElement(g,"click",function(u){(n.apply_for_similar||u.target===u.currentTarget)&&k(u.target,n)}))},q=function(g){if("undefined"===g)return!1;g=g.getBoundingClientRect();var n=g.bottom;return 0<=g.top&&n<=window.innerHeight},p=function(g){for(var n=0;n<g.length;n++){var u=g[n],v=
document.querySelectorAll(u.dom_selector);if(null!==v)for(var w=0;w<v.length;w++)r(v[w],u)}},h=function(){for(var g=0;g<d.length;g++)for(var n=document.querySelectorAll(d[g].dom_selector),u=0;u<n.length;u++){var v=n[u],w=d[g];!v.visibilityTriggered&&q(v)&&(v.visibilityTriggered=!0,k(v,w))}},t=function(){var g=ORA.common.scrollEventCallback(a);window.scrollTracker[g]||(window.scrollTracker[g]=!0,h())},l=function(g,n,u){u=u.events;for(var v=0;v<u.length;v++){var w=u[v];if("click"===w.type)g.push(w);
else if("visibility"===w.type)n.push(w);else throw Error("Unsupported type "+w.type);}},x=function(g,n){var u=[],v=[],w=n.eventList;if(!w)return{visibilityConfig:v,clickConfig:u};for(var y=0;y<w.length;y++){var z=w[y];c(g,z.url)&&l(u,v,z)}return{visibilityConfig:v,clickConfig:u}},f=function(g){m=ORA.common._shallowMerge(m,g&&g.config||{});if(m.enable){a=m.scroll_frequency||1;g=x(document.location.protocol+"//"+document.location.hostname+document.location.pathname,m);var n=g.clickConfig;d=g.visibilityConfig;
p(n);h();ORA.common.addMutationObserver(g,function(u){p(u.clickConfig);h()});d&&0<d.length&&ORA.common.addEventListenersOnDOMElement(document,"scroll",t)}else ORA.Debug.debug("Behaviour Tracking Plugin not enabled")};ORA.regPlugin("sbt",f,{blockCollect:!1});ORA.analytics.plugins.simpleBehaviourTracking={};ORA.analytics.plugins.simpleBehaviourTracking.isConfigApplicable=c;ORA.analytics.plugins.simpleBehaviourTracking.isMatch=b;ORA.analytics.plugins.simpleBehaviourTracking.triggerEventWithBeaconProtocol=
e;ORA.analytics.plugins.simpleBehaviourTracking.clickHandler=k;ORA.analytics.plugins.simpleBehaviourTracking.init=f;ORA.analytics.plugins.simpleBehaviourTracking.isElementVisible=q;ORA.analytics.plugins.simpleBehaviourTracking.checkIfConfiguredElementsVisible=h;ORA.analytics.plugins.simpleBehaviourTracking.divideClickAndVisibilityConfigs=l;ORA.analytics.plugins.simpleBehaviourTracking.saveAllConfigApplicable=x})();
(function(){var m,d,a,b,c={enable:!0,cookieDays:365,cookieName:"ORAPERSIST",cookieDomain:"",params:"dcsvid infy riid rid customer_id elqCID elq_cid elq_mid product".split(" "),defPrefix:"DCSext",priority:100,useMostRecent:!0,lowerCaseValues:!0},e=new function(){var p=this;p.getQueryParamsMap=function(h,t){var l=ORA.common.extendObject({}),x=[],f=h,g=t||c;try{l=JSON.parse(h)}catch(w){"string"===typeof f&&(f=f.replace(/^[&\?\s]+/i,""),x=f.split("\x26"));for(var n=0,u=x.length;n<u;++n){f=x[n];f=f.split("\x3d");
var v=f[0].toLowerCase();""!==v&&(l[v]=g.lowerCaseValues?decodeURIComponent(f[1].toLowerCase()):decodeURIComponent(f[1]))}}return l};p.getValueOfExistingParam=function(h,t,l,x,f){var g=null,n,u=f||c;h.forEach(function(v,w){if(w.toLowerCase()===l||w.toLowerCase()===t)n=u.lowerCaseValues&&"string"===typeof v?v.toLowerCase():v});n?(g=n,ORA.Debug.debug("Taking current value from QRY: "+l+'\x3d"'+g+'"',"ANA - pp")):null!==x.getParam(l)&&(g=x.getParam(l),ORA.Debug.debug("Taking current value from dcsMsg: "+
l+'\x3d"'+g+'"',"ANA - pp"));g&&ORA.Debug.debug("Param (current value): "+l+'\x3d"'+g+'"',"ANA - pp");return g};p.getParamValue=function(h,t,l,x,f){h=p.getValueOfExistingParam(h,t,l,x);l=p.getQueryParam(f,l);null===h||"undefined"===h||!c.useMostRecent&&null!==l||(l=h);return l};p.getQueryParam=function(h,t){var l=null;h.forEach(function(x,f){f.toLowerCase()===t&&(l=x)});return l};p.applyPreviouslyPersistedParamsValues=function(h,t,l){for(var x="",f=ORA.common.extendObject({}),g=0,n=c.params.length;g<
n;++g){var u=c.params[g],v=u;ORA.Debug.info("Processing param: "+u,"ANA - pp");t[u]=p.getParamValue(h,u,v,l,t);var w=p.getQueryParam(t,u);w&&(ORA.Debug.info("Overriding MSG value with saved value: "+v+'\x3d"'+w+'"',"ANA - pp"),l.setParam(v,w,!0),f[v]=w);(v=p.getQueryParam(h,u)||p.getQueryParam(h,v))&&ORA.common.QueryParamCache.set(u,v)}f.forEach(function(y,z){x=x+"\x26"+z+"\x3d"+encodeURIComponent(y)});return x=x.replace(/^[&\?\s]+/i,"")};p.arrayIndexOf=function(h,t){if(!ORA.analytics.isArray(h))return-1;
if(Array.prototype.indexOf)return h.indexOf(t);for(var l=0,x=h.length;l<x;l++)if(h[l]===t)return l;return-1}},k=function(){this.getCookieDomain=function(){var p="",h=c.cookieDomain;h==location.hostname&&(h="");a&&a.FPCConfig&&a.FPCConfig.domain&&(p=a.FPCConfig.domain);ORA.Debug.debug("sDCSDomain: "+p,"ANA - pp");h&&"."===h.charAt(0)&&(h=h.slice(1));return c.cookieDomain?h:p?p:ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain()}},r=function(){this.savePersistedParams=function(p,h,t,l){var x=new Date;
x.setDate(x.getDate()+l);l=";domain\x3d"+t+";path\x3d/;expires\x3d"+x.toUTCString();t||(l=";path\x3d/;expires\x3d"+x.toUTCString());m(p,h,l)};this.getPersistedParams=function(p){var h=ORA.common.extendObject({});p=d(p);return null===p?h:h=e.getQueryParamsMap(p)}};var q=new function(){var p=this,h=new k,t=new r;p.ppMutation=function(l){var x=ORA.common.QueryParamCache.getCache(),f=t.getPersistedParams(c.cookieName);ORA.Debug.debug("QRY params: "+JSON.stringify(x),"ANA - pp");l=e.applyPreviouslyPersistedParamsValues(x,
f,l);b||(b=h.getCookieDomain(),ORA.Debug.debug("Cookie domain to use: "+b,"ANA - pp"));ORA.Debug.debug("Saving persistent params in cookie: "+c.cookieName+'\x3d"'+l+'"',"ANA - pp");t.savePersistedParams(c.cookieName,l,b,c.cookieDays)};p.ppInit=function(l,x){var f=l.config;if(f){for(var g in f)f.hasOwnProperty(g)&&(c[g]=f[g]);f=[];g=0;for(var n=c.params.length;g<n;++g)c.params[g]=c.params[g].toLowerCase(),f.push(c.params[g]);c.params=f}ORA.Debug.info("initializing...","ANA - pp");c.enable?c.params&&
0!==c.params.length?(ORA.Debug.debug("params to persist: "+c.params.join(", "),"ANA - pp"),m=ORA.analytics.setCookie,d=ORA.analytics.getCookieRaw,a=ORA.analytics.dcsRef,ORA.analytics.addMutation("persistParams",p.ppMutation,3)):ORA.Debug.debug("no persist params defined - will not run","ANA - pp"):ORA.Debug.debug("disabled in config - will not run","ANA - pp");c.blockCollect&&x&&x()}};ORA.regPlugin("pp",q.ppInit);ORA.plugins||(ORA.plugins={});ORA.plugins.pp||(ORA.plugins.pp={});ORA.Debug.debug("PP: Plugin initialized",
"ANA - pp");ORA.plugins.pp.Domain=new k;ORA.plugins.pp.PersistParams=new r;ORA.plugins.pp.OraclePP=q;ORA.plugins.pp.helper=e;ORA.plugins.pp.config=c})();ORA.Debug.debug("PP: Loading Plugin","ANA");
(function(){var m={sampleRate:50,maxT:2,waitTime:150,assetFilter:".*js",enable:!0,enablePerf:!1,perfLimit:50},d={"wt.tm_pageReady":["loadEventEnd","navigationStart"],"wt.tm_pageRedir":["redirectEnd","redirectStart"],"wt.tm_serverConn":["connectEnd","connectStart"],"wt.tm_pageDns":["domainLookupEnd","domainLookupStart"],"wt.tm_serverResponse":["responseEnd","responseStart"],"wt.tm_pageDownload":["responseEnd","requestStart"],"wt.tm_domContentLoaded":["domContentLoadedEventEnd","navigationStart"],"wt.tm_redirect":["redirectEnd",
"redirectStart"]},a={"ora.tm_transferSize":["transferSize"],"ora.tm_encodedSize":["encodedBodySize"],"ora.tm_connect":["connectEnd","connectStart"],"ora.tm_domainLookup":["domainLookupEnd","domainLookupStart"],"ora.tm_duration":["duration"],"ora.tm_response":["responseEnd","responseStart"],"ora.tm_assetName":["name"]},b=function(q){return!isNaN(parseFloat(q))&&isFinite(q)},c=function(q,p,h){for(var t in d)d.hasOwnProperty(t)&&void 0!==p[d[t][0]]&&(q[t]=Number((p[d[t][0]]-p[d[t][1]])/1E3).toFixed(3),
q[t]>h&&delete q[t]);return q},e=function(q,p){var h=q.timing,t={};if(0===h.navigationStart)return t;t=c(t,h,p);t["wt.dl"]=70;t["wt.tm_tv"]="1.0.4";if(!performance||void 0===performance.getEntries||0===performance.getEntries().length||!m.enablePerf)return ORA.Debug.debug("Browser does not support page performance monitoring or performance monitoring is disabled","PLT_ANA"),t;h=performance.getEntries()||[];var l=[];l["ora.tm_cached"]=[];l["ora.tm_start"]=[];for(var x=0,f=0;f<h.length&&x<m.perfLimit;f++)if((new RegExp(m.assetFilter)).test(h[f].name)){x++;
var g=void 0,n=l,u=f,v=h;for(g in a)if(a.hasOwnProperty(g)){var w=n,y=g,z=u,A=v;w[y]=w[y]||[];void 0!==A[z][a[y][0]]?2===a[y].length?w[y].push(Number(A[z][a[y][0]]-A[z][a[y][1]]).toFixed(3)):b(A[z][a[y][0]])&&"transferSize"!==a[y][0]?w[y].push(Number(A[z][a[y][0]]).toFixed(3)):b(A[z][a[y][0]])?w[y].push(Number(A[z][a[y][0]]).toFixed(0)):0<A[z][a[y][0]].length?w[y].push(A[z][a[y][0]]):w[y].push(""):w[y].push("")}void 0!==h[f].transferSize&&0<h[f].transferSize?l["ora.tm_cached"].push("1"):l["ora.tm_cached"].push("0");
0!==f?l["ora.tm_start"].push(Number(h[f].startTime-h[0].responseEnd).toFixed(3)):l["ora.tm_start"].push(Number(0).toFixed(3))}for(var B in l)l.hasOwnProperty(B)&&(t[B]=l[B].join(";"));return t},k=function(q,p){setTimeout(function(){var h=e(q,p);"wt.tm_pageLoad wt.tm_pageRedir wt.tm_serverConn wt.tm_pageDns wt.tm_serverResponse wt.tm_pageDownload wt.tm_domContentLoaded wt.tm_pageReady".split(" ").forEach(function(t){0>h[t]&&(delete h[t],ORA.Debug.debug("PLT - Removing data - negative numbers found "+
t+"\x3d"+h[t],"PLT_ANA"),ORA.Debug.debug("PLT - This is typically because the wait time it too short","PLT_ANA"))});ORA.Debug.debug("PLT - Sending PLT data "+JSON.stringify(h,null,4),"PLT_ANA");ORA.click({data:h})},m.waitTime)},r=function(q){try{var p=window.performance||window.webkitPerformance;ORA.Debug.debug("PLT - Initializing","PLT_ANA");var h=q.config,t;for(t in m)m.hasOwnProperty(t)&&void 0!==h[t]&&(m[t]=h[t]);if(!m.enable||!p){ORA.Debug.debug("PLT - Exiting - disables or no browser support for timing",
"PLT_ANA");return}var l=6E4*m.maxT;0<m.sampleRate-100*Math.random()&&("complete"===document.readyState?k(p,l):window.addEventListener?window.addEventListener("load",k(p,l)):window.attachEvent("onload",k(p,l)))}catch(x){ORA.Debug.debug("PLT - Init error","PLT_ANA")}ORA.Debug.debug("PLT - Init complete","PLT_ANA")};ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.pageLoadTiming={};ORA.analytics.plugins.pageLoadTiming.getTiming=e;ORA.analytics.plugins.pageLoadTiming.init=r;ORA.analytics.plugins.pageLoadTiming.addPageResults=
c;ORA.analytics.plugins.pageLoadTiming.addPageLoadtrack=k;ORA.analytics.plugins.pageLoadTiming.cfg=m;ORA.regPlugin("plt",r)})();ORA.setExecuteState("analytics","ready");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_LOAD_COMPLETE,ORA.Event.STATUS_SUCCESS),!0);