DECLARE
CURSOR EC IS SELECT * FROM DEPT;
BEGIN
FOR V_EC IN EC
LOOP
DBMS_OUTPUT.PUT_LINE('DEPTNO='||V_EC.DEPTNO);
DBMS_OUTPUT.PUT_LINE('DNAME='||V_EC.DNAME);
DBMS_OUTPUT.PUT_LINE('LOC='||V_EC.LOC);
END LOOP;
END;


